### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/bmi-calculator-python#76]
**Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

### 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}
Good Job!

### 1. GitHub actions workflow for continuous integration
rubric={mechanics:10}
Good Job!
### 2. GitHub actions workflow for continuous deployment
rubric={mechanics:10}
Good Job!

### 3. Documentation
rubric={reasoning:10}

- The documentation build with ReadtheDocs is not available (no link on `GitHub` or in the `README.md` file) - **-1 reasoning**

**Comment:** While the README does have a badge that links to the ReadtheDoc, would be good to add an explicit link somewhere in the README.

## Specific expectations for this milestone 
rubric={mechanics:10}

- There isn't a milestone called `milestone3`. - **mechanics -2**

**Comment** No issues in milestone3 milestone

## Submission instructions
rubric={mechanics:10}
Good Job!

**Comment by netsgnut** [comment]
Thanks for the review! We have tagged the issues in the relevant repositories to the milestones, and I am preparing a PR to add an explicit docs link to README. Closing this for now. Thanks!
